# Generated by Django 6.0 on 2026-01-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Player ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Player full name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Player last name')),
                ('first_name', models.CharField(max_length=50, verbose_name='Player first name')),
                ('jersey', models.CharField(max_length=10, null=True, verbose_name='Player jersey number')),
                ('is_active', models.BooleanField(verbose_name='Player currently playing')),
                ('headshot', models.URLField(verbose_name='Player image')),
                ('year_start', models.CharField(max_length=50, verbose_name='Player starting year')),
                ('year_end', models.CharField(max_length=50, verbose_name='Player last year')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Team ID')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Team full name')),
                ('abbreviation', models.CharField(max_length=50, null=True, verbose_name='Team abbreviation')),
                ('nickname', models.CharField(max_length=50, null=True, verbose_name='Team nickname')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='Team city')),
                ('state', models.CharField(max_length=50, null=True, verbose_name='Team state')),
                ('year_founded', models.IntegerField(null=True, verbose_name='Team year founded')),
                ('logo', models.URLField(null=True, verbose_name='Team Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=30, verbose_name='Season statistic')),
                ('ppg', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Points per game')),
                ('rpg', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Rebounds per game')),
                ('apg', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Assists per game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=30, verbose_name='Season statistic')),
                ('conference', models.CharField(max_length=20, verbose_name='Team conference')),
                ('conference_record', models.CharField(max_length=20, verbose_name='Team conference record')),
                ('division_record', models.CharField(max_length=20, verbose_name='Team division record')),
                ('wins', models.IntegerField(verbose_name='Team wins')),
                ('losses', models.IntegerField(verbose_name='Team losses')),
                ('winrate', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Team win rate')),
                ('home', models.CharField(max_length=20, verbose_name='Team Home Record')),
                ('road', models.CharField(max_length=20, verbose_name='Team Road Record')),
                ('last10', models.CharField(max_length=20, null=True, verbose_name='Team Last 10 Games Standing')),
                ('overtime', models.CharField(max_length=20, verbose_name='Team Overtime Count')),
                ('winstreak', models.CharField(max_length=20, null=True, verbose_name='Team win streak')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team'),
        ),
    ]
