# Generated by Django 6.0 on 2026-01-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Standings',
            new_name='Standing',
        ),
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistic',
        ),
    ]
